title: "xf_blog"
description: "jekyll blog"

lang: zh-CN

baseurl: ""
url: "https://xfcnl.github.io"

theme: jekyll-theme-primer
plugins:
  - jekyll-feed
  - jekyll-sitemap

permalink: /tech/:name/

netease_player:
  enable: true
  playlist_id: "8285330087"
  fixed: true
  mini: true
  theme: "#e74c3e"
  volume: 0.5
  order: "list"

github: [metadata]

collections:
  note:
    output: true
    permalink: /note/:name/
